### ISSUE TITLE
Error with $_SERVER

### ISSUE THREAD

**Issue by aksld** [lucatume/wp-browser#417] opened 2020-06-03 17:14 UTC
Hello,

When executing the following command :

`vendor/bin/codecept run wpunit --bootstrap /app/vendor/autoload.php`

I have this error :

 Cannot determine time at which the request started because $_SERVER['REQUEST_TIME_FLOAT'] is not of type float 

Do you know this error ?

Thanks

**Comment by lucatume** [comment] 2020-06-04 07:42
Hi @aksld,

I've seen this error pop-up before in more recent versions of PHPUnit; could you please provide:

* Codeception version
* PHPUnit version
* wp-browser version
* PHP version
* a brief description of your local testing setup

That would help me debug the issue and help you, thanks.

**Comment by aksld** [comment] 2020-06-04 08:49
Hi @lucatume 

Composer.json :

```{
	"require-dev": {
		"phpunit/phpunit": "^9",
		"lucatume/wp-browser": "^2.5",
		"codeception/module-asserts": "^1.0",
		"codeception/module-phpbrowser": "^1.0",
		"codeception/module-webdriver": "^1.0",
		"codeception/module-db": "^1.0",
		"codeception/module-filesystem": "^1.0",
		"codeception/module-cli": "^1.0",
		"codeception/util-universalframework": "^1.0"
	}
}```

I'm using php 7.4

My local testing setup is Lando (docker).

I have two mysql database : wordpress and tests.

Tell me if you need more informations, thanks.

**Comment by lucatume** [comment] 2020-06-04 16:58
@aksld thanks for the information, this is already very helpful.

I will take a look and let you know.

**Comment by lucatume** [comment] 2020-06-04 21:23
Hi @aksld,

I've pushed a _possible_ fix for this issue in https://github.com/lucatume/wp-browser/pull/421

Would you mind testing this out pulling it using:

```bash
composer require --dev lucatume/wp-browser:dev-fix-417-server-request-time
```

And let me know if this fixes it?

**Comment by aksld** [comment] 2020-06-05 13:48
I have the same error :(

**Comment by lucatume** [comment] 2020-06-06 18:41
Darn, thanks for the feedback, I really did hope this would fix it.

I cannot currently reproduce, so this is a bit hard to debug...

**Comment by aksld** [comment] 2020-06-06 21:54
I want to help you but I don’t know how :(

Maybe you can take remote control of my computer to see on live ?

**Comment by lucatume** [comment] 2020-06-08 14:42
Hi @aksld,

thanks for offering a live debug, I'll take you up on your offer if the latest push does not fix the issue.

Could you try to update the branch using:

```bash
composer require --dev lucatume/wp-browser:dev-fix-417-server-request-time
```

And let me know if that fixes the issue?

For background: due to how the `WPTestCase` class works (w/ `$backupGlobals = false`) if the `$_SERVER` global is modified during tests, then it will not be correctly set after.
See [this thread](https://github.com/sebastianbergmann/phpunit/issues/3026#issuecomment-368842252).

**Comment by aksld** [comment] 2020-06-11 09:11
0 error !

Perfect !!!

**Closed** 2020-06-11 09:31 UTC
