### ISSUE TITLE
Bootstrap fails

### ISSUE THREAD

**Issue by awlwordpress** [lucatume/wp-browser#15] opened 2015-06-03 01:03 UTC
I'm trying to run the bootstrap command in a clean WordPress installation and getting this error: Helpers path is not defined by key "paths: helpers".  The bootstrap process quits after the error.  Am I doing something wrong?

Here's the full output:

```
$ php ./vendor/bin/wpcept bootstrap
Initializing Codeception in /

PHP Notice:  Undefined property: Codeception\Command\WPBootstrap::$supportDir in /vendor/lucatume/wp-browser/src/WPBootstrap.php on line 24

Notice: Undefined property: Codeception\Command\WPBootstrap::$supportDir in /vendor/lucatume/wp-browser/src/WPBootstrap.php on line 24
PHP Notice:  Undefined property: Codeception\Command\WPBootstrap::$envsDir in /vendor/lucatume/wp-browser/src/WPBootstrap.php on line 25

Notice: Undefined property: Codeception\Command\WPBootstrap::$envsDir in /vendor/lucatume/wp-browser/src/WPBootstrap.php on line 25
File codeception.yml created       <- global configuration
tests/unit created                 <- unit tests
tests/unit.suite.yml written       <- unit tests suite configuration
tests/functional created           <- functional tests
tests/functional.suite.yml written <- functional tests suite configuration
tests/acceptance created           <- acceptance tests
tests/acceptance.suite.yml written <- acceptance tests suite configuration
tests/_bootstrap.php written <- global bootstrap file
Building initial Tester classes



  [Codeception\Exception\Configuration]
  Helpers path is not defined by key "paths: helpers"



bootstrap [-ns|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [--compat] [--customize] [--] [<path>]
```

**Comment by lucatume** [comment] 2015-06-04 09:32
Ok, that should be fixed now, thanks for pointing it out!

**Comment by rahularyan** [comment] 2016-02-12 17:30
Sill having this issue.
`Notice: Undefined property: Codeception\Command\WPBootstrapPyramid::$supportDir in ..\Composer\vendor\lucatume\wp-brows
er\src\Codeception\Command\WPBootstrap.php on line 26

Call Stack:
    0.0003     255544   1. {main}() ..\Composer\vendor\lucatume\wp-browser\wpcept:0
    0.0643    3778136   2. Symfony\Component\Console\Application->run() ..\Composer\vendor\lucatume\wp-browser\wpcept:3
6
    0.0732    4205768   3. Symfony\Component\Console\Application->doRun() ..\Composer\vendor\symfony\console\Applicatio
n.php:123
    0.0740    4206704   4. Symfony\Component\Console\Application->doRunCommand() ..\Composer\vendor\symfony\console\App
lication.php:192
    0.0740    4207232   5. Symfony\Component\Console\Command\Command->run() ..\Composer\vendor\symfony\console\Applicat
ion.php:844
    0.0746    4211568   6. Codeception\Command\WPBootstrap->execute() ..\Composer\vendor\symfony\console\Command\Comman
d.php:259
    0.0765    4213568   7. Codeception\Command\WPBootstrap->createGlobalConfig() ..\Composer\vendor\lucatume\wp-browser
\src\Codeception\Command\WPBootstrap.php:136

File codeception.yml created       <- global configuration

  [Symfony\Component\Console\Exception\InvalidArgumentException]
  The "empty" option does not exist.

bootstrap:pyramid [-ns|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [--compat] [--customize] [--] [<path>]
`

**Comment by lucatume** [comment] 2016-02-15 10:37
The issue was for the `wpcept bootstrap` command but this one seems to be about the `wpcept bootstrap:pyramid` one; if so please open a new issue and detail the steps to reproduce including wp-browser version number.

**Comment by rahularyan** [comment] 2016-02-15 10:44
Happens with both `wpcept bootstrap` and ` wpcept bootstrap:pyramid`. This issue only appear in windows.

**Comment by lucatume** [comment] 2016-02-15 16:06
Did you pull the latest version of wp-browser?

**Comment by rahularyan** [comment] 2016-02-15 16:12
Yes, Just pulled today.. and trying.
At the moment I am trying in our staging ubuntu server, `wpcept bootstrap` and `wpcept bootstrap:pyramid` works properly.
Having hard time trying to login, no matter what I do i cannot login (I will open a new if you want):

`$I = new AcceptanceTester($scenario);

$I->amGoingTo('log in as admin');
$I->amOnPage('/wp-login.php');
$I->fillField('Username', 'admin');
$I->fillField('Password','admin');
$I->click('Log In');
$I->see('Dashboard');
// login as administrator
$I->amOnPluginsPage();
$I->seePluginActivated('anspress-question-answer');`

Always output wrong password for user admin. can you help?
Thanks

**Comment by lucatume** [comment] 2016-02-16 08:29
Glad to hear issue is moving forward.
If you use WPBrowser or WPWebDriver modules then there is the `loginAsAdmin` method.
Let me know if that too is raising issues. Also note that the database should contain the md5 version of the password

**Closed by lucatume** 2016-02-16 08:29 UTC
Labels: bug

**Comment by Mte90** [comment] 2016-04-27 18:21
I get this error:
```
PHP Notice:  Undefined property: Codeception\Command\WPBootstrap::$supportDir in /home/www/VVV/www/woocommerce/htdocs/wp-content/plugins/woocommerce-xxxxxx/vendor/lucatume/wp-browser/src/Codeception/Command/WPBootstrap.php on line 26
```

**Comment by lucatume** [comment] 2016-04-27 18:52
Executing `wpcept bootstrap`?
Seems like an outdated Codeception error: is everything (Composer, Codeception and WPBrowser) wp to date?

**Comment by Mte90** [comment] 2016-04-27 19:17
I do:
```
composer require --dev lucatume/wp-browser
./vendor/bin/wpcept bootstrap
```
I don't know if it is php 7 that generate this problem but I don't think so much

**Comment by Mte90** [comment] 2016-04-27 19:19
With ```./vendor/bin/codecept bootstrap``` i don't have errors.

**Comment by Mte90** [comment] 2016-04-27 19:24
Uhm if i take the composer files from an old plugin this works without problems.

**Comment by Mte90** [comment] 2016-04-27 19:26
So i tried now with the composer.json from https://github.com/lucatume/idlikethis/ and i get the same errors.
This is the output from composer:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing xrstf/composer-php52 (v1.0.20)
    Loading from cache

  - Installing lucatume/di52 (dev-master 8778d42)
    Cloning 8778d42c9b2b0896832a59faaf6c2bde228dbf95

  - Installing smarty/smarty (v3.1.29)
    Loading from cache

  - Installing xamin/handlebars.php (v0.10.3)
    Loading from cache

  - Installing hautelook/phpass (0.3.3)
    Loading from cache

  - Installing illuminate/support (v4.2.17)
    Loading from cache

  - Installing mikemclin/laravel-wp-password (2.0.0)
    Loading from cache

  - Installing symfony/filesystem (v2.8.4)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.1.1)
    Loading from cache

  - Installing symfony/dom-crawler (v2.8.4)
    Loading from cache

  - Installing symfony/css-selector (v2.8.4)
    Loading from cache

  - Installing symfony/browser-kit (v2.8.4)
    Loading from cache

  - Installing symfony/yaml (v2.8.4)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.8.4)
    Loading from cache

  - Installing symfony/console (v2.8.4)
    Loading from cache

  - Installing symfony/finder (v2.8.4)
    Loading from cache

  - Installing guzzlehttp/streams (2.1.0)
    Loading from cache

  - Installing guzzlehttp/guzzle (4.2.3)
    Loading from cache

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/environment (1.3.5)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.2.4)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing sebastian/exporter (1.2.1)
    Loading from cache

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (2.0.4)
    Loading from cache

  - Installing phpspec/prophecy (v1.6.0)
    Loading from cache

  - Installing phpunit/php-timer (1.0.7)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Loading from cache

  - Installing phpunit/phpunit (4.8.24)
    Loading from cache

  - Installing facebook/webdriver (v0.6.0)
    Loading from cache

  - Installing codeception/codeception (2.0.1)
    Loading from cache

  - Installing bacon/bacon-string-utils (1.0.3)
    Loading from cache

  - Installing lucatume/wp-browser (1.10.7)
    Loading from cache

  - Installing lucatume/args (1.0.1)
    Loading from cache

  - Installing antecedent/patchwork (1.3.5)
    Loading from cache

  - Installing lucatume/function-mocker (1.0.5)
    Loading from cache

symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
symfony/browser-kit suggests installing symfony/process ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing psr/log (For using the console logger)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
codeception/codeception suggests installing codeception/phpbuiltinserver (Extension to start and stop PHP built-in web server for your tests)
codeception/codeception suggests installing codeception/specify (BDD-style code blocks)
codeception/codeception suggests installing codeception/verify (BDD-style assertions)
codeception/codeception suggests installing monolog/monolog (Log test steps)
bacon/bacon-string-utils suggests installing zendframework/zend-filter (To use the Slugifier as a Zend\Filter instance)
Writing lock file
Generating autoload files
> xrstf\Composer52\Generator::onPostInstallCmd
> xrstf\Composer52\Generator::onPostInstallCmd
```

**Comment by Mte90** [comment] 2016-04-27 19:37
The difference that i can see are on di52:
```
  - Updating lucatume/di52 dev-master (1e3903a => 8778d42)
    Checking out 8778d42c9b2b0896832a59faaf6c2bde228dbf95
```

**Comment by lucatume** [comment] 2016-04-28 09:20
I don't get any error. What's the `minimum-stability` set in the `composer.json` file?

**Comment by Mte90** [comment] 2016-04-28 10:27
It is stable but I can see there is some different versions of the packages so I am looking for that.

**Comment by Mte90** [comment] 2016-04-28 12:32
As i can see the problem is codeception that is download as 2.0.1 version while with the 2.1.7 the problem not happen.
If i try a composer update i get a conflict of dependence:
```
  Problem 1
    - Conclusion: don't install codeception/codeception 2.1.8
    - Conclusion: remove facebook/webdriver v0.6.0
    - Installation request for codeception/codeception ^2.1.7 -> satisfiable by codeception/codeception[2.1.7, 2.1.8].
    - Conclusion: don't install facebook/webdriver v0.6.0
    - codeception/codeception 2.1.7 requires facebook/webdriver >=1.0.1 <2.0 -> satisfiable by facebook/webdriver[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - Can only install one of: facebook/webdriver[1.0.1, v0.6.0].
    - Can only install one of: facebook/webdriver[1.0.2, v0.6.0].
    - Can only install one of: facebook/webdriver[1.0.3, v0.6.0].
    - Can only install one of: facebook/webdriver[1.0.4, v0.6.0].
    - Can only install one of: facebook/webdriver[1.1.0, v0.6.0].
    - Can only install one of: facebook/webdriver[1.1.1, v0.6.0].
    - Installation request for facebook/webdriver == 0.6.0.0 -> satisfiable by facebook/webdriver[v0.6.0].
```
But finally I've done with a force on install the 1.2.8 version of codeception.
