### ISSUE TITLE
[BUG] @testdox annotation not working for test descriptions

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#645] opened 2023-09-29 09:22 UTC
I've tried implementing the `@testdox` annotation to rename my test class (well to make the output a bit nicer), but it's not doing anything when I run the tests (the test neme is just parsed test class without the test prefix).

I'm not sure if this is a codeception thing (it must be), but is it possible to rename the output to something more readable, or do I need to have my test class longer in order to display what I want?

Thanks!

**Comment by lucatume** [comment] 2023-09-29 11:53
If it does not work on a test case generated with `vendor/bin/codecept g:test ...`, it's probably a [Codeception issue](https://github.com/Codeception/Codeception/issues/2615).

Please provide a minimum fixture to reproduce the issue.

**Comment by dingo-d** [comment] 2023-09-29 12:07
I generated a unit test using `vendor/bin/codecept generate:test Unit Test`

```php
<?php


namespace Tests\Unit;

use Tests\Support\UnitTester;

class Test extends \Codeception\Test\Unit
{

    protected UnitTester $tester;

    protected function _before()
    {
    }

	/**
	 * @testdox This is some feature test!
	 */
    public function testSomeFeature()
    {
		$this->assertTrue(true);
    }
}
```

When running the Unit test suite, I still get

```bash
✔ Test: Some feature(0.00s)
```

And I expected it to be

```bash
✔ Test: This is some feature test!(0.00s)
```

**Comment by lucatume** [comment] 2023-10-03 06:53
I've created a test repository using `codeception/codeception` as a dev dependency and do not see Testdox being supported.
This looks like an issue with Codeception, not this project, closing.

**Closed by lucatume** 2023-10-03 06:53 UTC
Labels: info-required
