### ISSUE TITLE
composer update: no matching package found.

### ISSUE THREAD

**Issue by mipon** [lucatume/wp-browser#12] opened 2015-03-12 02:28 UTC
Hello,

I'm trying to set up your module. 

1. Created an empty directory.
2. Created `composer.json` with the followings:
    
    ```
   {
        "require-dev":{
              "lucatume/wp-browser": "master@dev"
        }
    }
   ```
    
3. In the directory performed  `composer update`

It gives the following error.

> \>composer update
>  Loading composer repositories with package information
>  Updating dependencies (including require-dev)
>  Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
>     - Installation request for lucatume/wp-browser master@dev -> satisfiable by lucatume/wp-browser[dev-master].
>     - lucatume/wp-browser dev-master requires badcow/lorem-ipsum dev-master -> no matching package found.
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
> 
> Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Am I doing it right or missing something?

**Comment by lucatume** [comment] 2015-03-12 13:04
Probably a dependency issue in the library, will look into it.
In the meanwhile a quick work around is to require `badcow/lorem-ipsum` before wp-browser as well

**Comment by mipon** [comment] 2015-03-13 02:39
Thanks, this worked.

```
{
    "require": {
        "badcow/lorem-ipsum": "dev-master"
    },
    "require-dev":{
        "lucatume/wp-browser": "master@dev"          
    }
}
```

**Comment by lucatume** [comment] 2015-06-04 09:34
Again I could not reproduce: still getting that?

**Comment by maxchirkov** [comment] 2015-08-25 15:52
I am getting this error as well when trying to run composer install.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lucatume/wp-browser dev-master requires badcow/lorem-ipsum ~1.0 -> no matching package found.
    - lucatume/wp-browser dev-master requires badcow/lorem-ipsum ~1.0 -> no matching package found.
    - Installation request for lucatume/wp-browser master@dev -> satisfiable by lucatume/wp-browser[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by lucatume** [comment] 2015-10-16 08:05
I've removed that dependency and the issue should be fixed.

**Closed by lucatume** 2015-10-16 08:05 UTC
Labels: bug
