### ISSUE TITLE
[BUG] Side effects in files loaded during autoloading of `WPTestCase` break PHPStan scanning

### ISSUE THREAD

**Issue by johnbillion** [lucatume/wp-browser#554] opened 2022-01-07 01:34 UTC
This is a meta issue seemingly unrelated to any particular configuration.

**Describe the bug**

I have a project that is tested using WPBrowser and PHPStan. When scanning the project's integration test files with PHPStan, a PHP fatal error is triggered which prevents the scanning from working. This error is triggered inside the `src/includes/bootstrap.php` file from WPBrowser.

Why does this happen? It happens because PHPStan uses Composer autoloading during its test run, and if you instruct PHPStan to scan your test files then one of the classes that gets autoloaded is the `\Codeception\TestCase\WPTestCase` class. Inside the file where this class lives, the `includes/bootstrap.php` gets included and this file has side effects. One of the side effects is to call the `tests_add_filter()` function which does not exist in this context, therefore triggering a PHP fatal error.

This is the line in question: https://github.com/lucatume/wp-browser/blob/f6abdab777e7e4230c2ea8dd112b25c6455e03b1/src/Codeception/TestCase/WPTestCase.php#L21-L23

**To Reproduce**

1. Set up a WPBrowser project that includes WordPress integration tests
2. Scan the project's test files with PHPStan
3. Observe an error from PHPStan similar to:  

       Error (Call to undefined function tests_add_filter()) thrown while looking for class ExtCPTs\Tests\Admin

Example failed test run here: https://github.com/johnbillion/extended-cpts/runs/4734079624?check_suite_focus=true

**Workaround**

Removing the `boostrap.php` include from here allows the PHPStan scanning and the integration tests to work, but I don't have any tests that run in isolation. Reading the surrounding comments and git history it seems this is needed for such tests.

Maybe this inclusion can be moved to the WPBrowser bootstrapping process so it's not included as part of the autoload process?

**Comment by ahegyes** [comment] 2022-01-13 14:30
I did encounter a similar bug today actually. I'm leaving the information here in case it's useful:

`PHP Fatal error:  Uncaught Error: Call to undefined function tests_add_filter() in /home/runner/work/wordpress-framework-bootstrapper/wordpress-framework-bootstrapper/vendor/lucatume/wp-browser/src/includes/bootstrap.php:61`

And I traced it back to release 3.0.18: https://github.com/lucatume/wp-browser/compare/3.0.17...3.0.18

According to the stack trace, it does originate in the `lucatume/wp-browser/src/Codeception/TestCase/WPTestCase.php` file at line 22. 

This affects my acceptance tests only, so this configuration: https://github.com/deep-web-solutions/wordpress-framework-bootstrapper/blob/master/tests/acceptance.suite.yml yet it does not affect my wpunit tests: https://github.com/deep-web-solutions/wordpress-framework-bootstrapper/blob/master/tests/wpunit.suite.yml

I thought at first it might be an issue with using the WPLoader as an isolated install or in 'loadOnly' mode, but removing those 2 config items did not fix the issue.

**Comment by lucatume** [comment] 2022-01-14 08:31
Thanks @ahegyes for the information, I will look into this and see what is going on.

**Comment by lucatume** [comment] 2022-01-14 08:42
The issue caused by the `tests_add_filter` function being called before its definition should have been fixed in [3.0.22](https://github.com/lucatume/wp-browser/releases/tag/3.0.22).

**Comment by ahegyes** [comment] 2022-01-14 11:58
Thanks for looking into this @lucatume ! Indeed, version 3.0.22 is working again for me :)

**Closed** 2022-02-01 09:24 UTC
Labels: bug
