### ISSUE TITLE
Out of memory on importing big dump file via populator

### ISSUE THREAD

**Issue by slaFFik** [lucatume/wp-browser#103] opened 2017-09-20 10:08 UTC
When trying to populate big sql dump (when running `codecept run acceptance`) I get this error:

```
Codeception PHP Testing Framework v2.3.5
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

VirtualAlloc() failed: [0x00000008] Not enough storage is available to process this command.
VirtualAlloc() failed: [0x00000008] Not enough storage is available to process this command.

Fatal error: Out of memory (allocated 8388608) (tried to allocate 1305528064 bytes) in ...\vendor\lucatume\wp-browser\src\Codeception\Module\WPDb.php on line 166
```

The filesize is 1,305,519,850 bytes, I put `memory_limit=2048M` in php.ini, so that should be enough. 
What are possible reasons of this failure?

My `acceptance.suite.yml` for `WPDb` module has this line:
```
populator: 'mysql -u $user -h $host $dbname < $dump'
```

**Comment by slaFFik** [comment] 2017-09-20 10:13
Why in general the dump file is read in memory when it should be just passed to in a path to a populator comment? Except replacing all the things (but I have disabled `urlReplacement`).

It seems I don't understand something obvious.

**Comment by slaFFik** [comment] 2017-09-20 10:17
Switching to `Db` instead of `WPDb` starts the importing (currently in progress).

Is it a good feature request to omit reading file in memory when no replacement is required?

**Comment by lucatume** [comment] 2017-09-20 10:30
This looks like a legit bug, thanks for reporting it.
I will look into that.

**Comment by slaFFik** [comment] 2017-09-22 13:53
What should I expect? 
As far as I can see in `master` the file will still be loaded in memory and a regexp to cleanup the comments will run. I will test it anyway a bit later.

**Comment by slaFFik** [comment] 2017-09-26 07:49
Tested `"lucatume/wp-browser": "dev-master"`.

> Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 1005282592 bytes) in ...\vendor\lucatume\wp-browser\src\Codeception\Module\WPDb.php on line 192

It's the regexp. So no luck, because the whole file is still loaded in memory instead directly passing to `populator`. 
So again,
Is it a good feature request to omit reading file in memory when no replacement is required? Do not strip comments, if there is a `populator` - pass to it without loading the file.

**Comment by lucatume** [comment] 2017-09-26 10:45
Thanks for taking the time to try it out and report.
Your suggestion makes sense: I've pushed the `no-dump-loading` branch, and that should address the issue.
Let me know if it works as intended; use `composer update lucatume/wp-browser:dev-no-dump-loading` to pull it in your project.

**Comment by lucatume** [comment] 2017-09-26 11:49
That makes, even more, sense; thank you. I've updated the branch to that code: I will test this a little more and then release.

**Comment by lucatume** [comment] 2017-09-26 14:16
Thanks again for your time; I've merged the fix into the `master` branch, and this is out in version `1.21.18`.

**Closed by lucatume** 2017-09-26 14:16 UTC
Labels: bug
